set(_AMENT_PACKAGE_NAME "roboparty_inference")
set(roboparty_inference_VERSION "1.2.0")
set(roboparty_inference_MAINTAINER "RoboParty <ZhihaoLiu_hit@163.com>")
set(roboparty_inference_BUILD_DEPENDS "rclcpp" "ament_index_cpp" "std_msgs" "sensor_msgs" "geometry_msgs" "std_srvs" "roboparty_imu" "roboparty_motors")
set(roboparty_inference_BUILDTOOL_DEPENDS "ament_cmake")
set(roboparty_inference_BUILD_EXPORT_DEPENDS "rclcpp" "ament_index_cpp" "std_msgs" "sensor_msgs" "geometry_msgs" "std_srvs" "roboparty_imu" "roboparty_motors")
set(roboparty_inference_BUILDTOOL_EXPORT_DEPENDS )
set(roboparty_inference_EXEC_DEPENDS "rclcpp" "ament_index_cpp" "std_msgs" "sensor_msgs" "geometry_msgs" "std_srvs" "roboparty_imu" "roboparty_motors")
set(roboparty_inference_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(roboparty_inference_GROUP_DEPENDS )
set(roboparty_inference_MEMBER_OF_GROUPS )
set(roboparty_inference_DEPRECATED "")
set(roboparty_inference_EXPORT_TAGS)
list(APPEND roboparty_inference_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
