set(_AMENT_PACKAGE_NAME "roboparty_motors")
set(roboparty_motors_VERSION "2.2.0")
set(roboparty_motors_MAINTAINER "RoboParty <ZhihaoLiu_hit@163.com>")
set(roboparty_motors_BUILD_DEPENDS "fmt" "spdlog" "eigen" "boost" "pybind11_vendor" "python3-dev")
set(roboparty_motors_BUILDTOOL_DEPENDS "ament_cmake")
set(roboparty_motors_BUILD_EXPORT_DEPENDS )
set(roboparty_motors_BUILDTOOL_EXPORT_DEPENDS )
set(roboparty_motors_EXEC_DEPENDS "fmt" "spdlog" "eigen" "boost" "python3")
set(roboparty_motors_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(roboparty_motors_GROUP_DEPENDS )
set(roboparty_motors_MEMBER_OF_GROUPS )
set(roboparty_motors_DEPRECATED "")
set(roboparty_motors_EXPORT_TAGS)
list(APPEND roboparty_motors_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
