set(_AMENT_PACKAGE_NAME "roboparty_imu")
set(roboparty_imu_VERSION "1.2.0")
set(roboparty_imu_MAINTAINER "RoboParty <2321901849@qq.com>")
set(roboparty_imu_BUILD_DEPENDS "fmt" "spdlog" "pybind11_vendor" "python3-dev")
set(roboparty_imu_BUILDTOOL_DEPENDS "ament_cmake")
set(roboparty_imu_BUILD_EXPORT_DEPENDS )
set(roboparty_imu_BUILDTOOL_EXPORT_DEPENDS )
set(roboparty_imu_EXEC_DEPENDS "fmt" "spdlog" "python3")
set(roboparty_imu_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(roboparty_imu_GROUP_DEPENDS )
set(roboparty_imu_MEMBER_OF_GROUPS )
set(roboparty_imu_DEPRECATED "")
set(roboparty_imu_EXPORT_TAGS)
list(APPEND roboparty_imu_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
